name: anony_chat
description: 익명메신저어플

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.0
  provider: ^4.3.2+1 #privder 패키지
  image_picker: ^0.6.7+4 #갤러리에서 사진 불러오는 패키지
  flutter_picker: ^1.1.5
  firebase_auth: ^0.18.0+1 #파이어베이스 인증 [*****플랫폼 별 설정 android, ios 필요*****]
  firebase_database: ^4.0.0 #파이어베이스 realtime database
  firebase_messaging: ^7.0.2 #[*****플랫폼 별 설정 android, ios 필요*****]
  cloud_firestore: ^0.14.2 #파이어베이스 데이터베이스 [*****플랫폼 별 설정 android, ios 필요*****]
  firebase_storage: ^4.0.0 #파이버에이스 파일저장소
  flutter_local_notifications: ^2.0.0
  async: ^2.3.0 #캐쉬
  fluttertoast: ^7.0.4 #플러터 토스트
  intl: ^0.16.1 # DateFormat
  json_annotation: ^3.0.1
  analyzer: ^0.39.0
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  hive_generator: ^0.7.2+1
  kakao_flutter_sdk: ^0.5.2 # 카카오톡 sdk
  url_launcher: ^5.7.2
  flutter_svg: ^0.19.1
  http: ^0.12.2
  iamport_flutter: ^0.9.13  #아임포트 결제서비스 [*****플랫폼 별 설정 android, ios 필요*****]
  new_version: ^0.0.5 #앱버전 가져오기
  permission_handler: ^5.0.1+1 #퍼미션 핸들러
  image_cropper: ^1.3.1 #이미지 자르기 패키지
  photo_view: ^0.10.2 #포토뷰
  cached_network_image: ^2.3.3 #캐쉬이미지
  grouped_list: ^3.5.0 #채팅 날짜별 그룹 리스트뷰

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.4.1
  build_runner: ^1.10.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto/Roboto-Regular.ttf
         - asset: assets/fonts/Roboto/Roboto-Italic.ttf
           style: italic
         - asset: assets/fonts/Roboto/Roboto-Bold.ttf
           weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
